### ISSUE TITLE
Thoughts on shortening project description

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Testing#4]
While the description in the top of the readme is very helpful for readers who have decided to dig in deeper, having that same length and detail of a description is hard to digest as the top-level repository description/about section. 

Obviously up for discussion here, but what about just a short description stating its for 'Tools for automated integration testing Sitefinity ASP.NET projects?'. Might go a little further and outright state the minimum version of sitefinity? (ie. 'Tools for automated integration testing Sitefinity `>= X` ASP.NET projects?'

**Comment by KevinBusch** [comment]
After creating the repo, I realized how long the description was compared to the other repos in the AndcultureCode repo list.  I'll update to make it simpler.  To your other point, I think it might be worth while to have the release numbers of this repo match the Sitefinity release numbers that the tests were built for.  Thoughts?

**Comment by wintondeshong** [comment]
That's an interesting thought around release numbers. If we are 100% confident that this test project will only ever work with a given sitefinity version (ie. not backwards or forwards compatible) then I'd say that makes sense. Otherwise, I feel it should be independent.

Either way, we should make it loud and clear what sitefinity version(s) we support near the very top of the project's README. Otherwise, we can annoy passers by.

**Comment by KevinBusch** [comment]
I'm 100% confident that this project will work for most, if not all of version 13 of sitefinity.  It might even support 12 as well but I wouldn't go that far in stating anything related to older releases.  Maybe it's best if we just call out the version number that this was tested against (v13.1.7421) and mention that it is likely backward compatible with all of the previous v13 releases but there is no plan to support backward compatibility.
