### ISSUE TITLE
Update link to AndcultureCode guide in CONTRIBUTING.md

### ISSUE THREAD

**Issue by HeyKos** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Testing#8]
The link to the AndcultureCode contributing guide is pointing to an old URL, and it has a space in the URL which causes it to be formatted improperly.

Currently: https://github.com/ AndcultureCode/AndcultureCode/blob/master/CONTRIBUTING.md

Should be: https://github.com/AndcultureCode/AndcultureCode/blob/main/CONTRIBUTING.md

**Comment by KevinBusch** [comment]
Good catch.  FYI You can fix the markdown files right in GitHub.  No need to create an issue out of it and push it through.  I'll take care of this.  Thanks!

**Comment by wintondeshong** [comment]
> Good catch. FYI You can fix the markdown files right in GitHub. No need to create an issue out of it and push it through. I'll take care of this. Thanks!

Yeah, so long as it is a quick and minor fix, I'm personally okay with using the UI. If the change's diff is of any significant size, we should create an issue and PR. Not sure about you guys, but I'm definitely better at formal languages :)
